version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: api
    env_file: [ ./src/backend/.env.docker ]
    ports:
      - "8080:8080"
    volumes:
      - ./src/backend:/app/src/backend
    depends_on:
      - mongo


  frontend:
    build:
      context: ./src/frontend/cso-frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./src/frontend/.env.docker
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      WDS_SOCKET_HOST: localhost
      WDS_SOCKET_PORT: 3000
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend/cso-frontend:/app
      - /app/node_modules
    depends_on:
      - api


volumes:
  mongo_data:
