services:
  mongo:
    image: mongo:6
    container_name: db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build:
      context: ./src/backend
    container_name: api
    env_file: [.env.docker]
    ports:
      - "8080:8080"
    depends_on: [mongo]

  frontend:
    build:
      context: ./src/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend/cso-frontend:/app/src
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - api

volumes:
  mongo_data:
  node_deps:
